### ISSUE TITLE
Causes Crash 

### ISSUE THREAD

**Issue by WillCooke** [FlagBrew/2048#1]
Installed 2048 from Switch appstore
Firmware: 5.1.0
Crashed Switch with error while playing using Joystick on left Joycon

**Comment by PyroFlareX** [comment]
Same with me, except no launch, it just crashes on startup.

**Comment by tkmzfan** [comment]
crash on startup too

**Comment by BernardoGiordano** [comment]
Did you download the latest version?

**Comment by tkmzfan** [comment]
I downloaded the one on switchbru.com

**Comment by BernardoGiordano** [comment]
So, the wrong one. Please download my software from my official pages only. https://github.com/BernardoGiordano/2048/releases/tag/1.0.0-1

**Comment by PyroFlareX** [comment]
I downloaded it from here though
and it still won't work
EDIT: didn't know there was an update, I downloaded the one on top
