### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by impeeza** [FlagBrew/2048#2]
Hi, I am using Switch Firmware 9.0.0 and Atmosphere 0.10.2, the game freezes on the main screen showing only 2 number boxes an the rest of the grid with no content, the application doesn't respond to any input.   there is any prerequisite? thanks.

**Comment by tokotchd** [comment]
I can second this issue.
Downloaded as part of the hekate + atmosphere 0.13 bundle (standard bundled download as of July 22, 2020) and the app either isn't responding to any input (touch screen, joycons, etc.) or is in a frozen state.

Home button, power button, and volume buttons are still working.

**Comment by impeeza** [comment]
Hi any advances?

**Comment by impeeza** [comment]
Sadly seems the repo is dead, a big hug from Colombia.

**Comment by impeeza** [comment]
Glad I got wrong, thanks a lot @BernardoGiordano for your effort.
